version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - PGPORT=5430
    ports:
      - 5430:5430
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
     - fastdelivery
  mongo:
    image: mongo
    container_name: mongo
    restart: on-failure
    ports:
      - 27018:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - fastdelivery
  elasticsearch:
   container_name: elasticsearch
   image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
   ports:
    - 9200:9200
   volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
   environment:
    - xpack.security.enabled=false
    # - xpack.watcher.enabled=false
    # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node
   networks:
    - elastic
  kibana:
   container_name: kibana
   image: docker.elastic.co/kibana/kibana:8.13.4
   ports:
    - 5601:5601
   depends_on:
    - elasticsearch
   environment:
    - ELASTICSEARCH_URL=http://localhost:9200
   networks:
    - elastic
volumes:
  postgres-data:  
  mongo-data:
  elasticsearch-data:
networks:
  fastdelivery:
    name:  fastdelivery
  elastic:
   driver: bridge

