version: '3.8'
name: fastdelivery

services:

  gateway:
    container_name: gateway
    image: ${DOCKER_REGISTRY-}gateway        
    networks:
     - fastdelivery
     - elastic
  order-service:
    container_name: order
    image: ${DOCKER_REGISTRY-}orderapi        
    networks:
     - fastdelivery
     - elastic
   

  tracking-service:
    container_name: tracking
    image: ${DOCKER_REGISTRY-}trackingapi       
    
    networks:
     - fastdelivery
     - elastic

  identity-service:
    container_name: identity
    image: ${DOCKER_REGISTRY-}identityapi
       
    depends_on:
      postgres:
        condition: service_healthy    
    networks:
     - fastdelivery
     - elastic
  webstatus:
    image: ${DOCKER_REGISTRY-}webstatus
    build:
      context: .
      dockerfile: src/web/WebStatus/Dockerfile
    networks:
     - fastdelivery
     - elastic

