version: '3.8'
name: fastdelivery

services:
  percel-service:
    container_name: parcel
    image: ${DOCKER_REGISTRY-}percelapi        
    networks:
     - fastdelivery

  identity-service:
    container_name: identity
    image: ${DOCKER_REGISTRY-}identityapi
       
    depends_on:
      postgres:
        condition: service_healthy
    #network_mode: "service:identity"
    networks:
     - fastdelivery

