version: '3.8'
name: fastdelivery

services:
  order-service:
    container_name: order
    image: ${DOCKER_REGISTRY-}orderapi        
    networks:
     - fastdelivery
     - elastic

  identity-service:
    container_name: identity
    image: ${DOCKER_REGISTRY-}identityapi
       
    depends_on:
      postgres:
        condition: service_healthy
    #network_mode: "service:identity"
    networks:
     - fastdelivery
     - elastic

