version: '3.8'

services:
  order-service:
    build:
      context: .
      dockerfile: src/services/orders/Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5101
      #- ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "5101:5101"
      - "50001:50001"
  order-service-dapr: 
    image: "daprio/daprd:latest" 
    command: [ "./daprd",
               "-app-id", "orderservice",                
               "-app-port", "5101",
               "-components-path", "/components"
                 ] 
    depends_on: 
     - order-service
     - redis
    network_mode: "service:order-service"
    volumes:
     - ./components:/components

  identity-service:
    build:
      context: .
      dockerfile: src/services/identity/Api/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_HTTP_PORTS=5103
    ports:
      - "5103:5103"
      - "50002:50001"
  identity-service-dapr: 
    image: "daprio/daprd:latest" 
    command: [ "./daprd",
               "-app-id", "identityservice",                
               "-app-port", "5103",
               "-components-path", "/components"
                 ] 
    depends_on: 
        - identity-service
        - redis
    network_mode: "service:identity-service"
    volumes:
     - ./components:/components
  redis:
   image: redis
   hostname: redis
   ports:
    - "6379:6379"
   networks:
     - fastdelivery
